### ISSUE TITLE
Make a duplicate of variants.vcf when testing

### ISSUE THREAD

**Issue by krrome** [kipoi/kipoi-veff#10]
py.test is not executed in the repository root hence file paths cannot be found

**Comment by Avsecz** [comment]
the repository root is correctly defined (otherwise `kipoi.get_model("model", source="dir")` would already fail). The problem is when multiple threads try to write remove and gzip 
 the vcf file `tests/models/rbp/example_files/variants.vcf`.

**Comment by Avsecz** [comment]
One solution to this problem is to copy the vcf file to a tmp path
