### ISSUE TITLE
Kipoi-veff fails silently when the input files don't exist

### ISSUE THREAD

**Issue by Avsecz** [kipoi/kipoi-veff#23]
The following command fails silently:

```bash
kipoi veff score_variants DeepBind/Homo_sapiens/TF/D00328.018_ChIP-seq_CTCF \
>    --dataloader_args='{"fasta_file": "input/hg19.chr22.fa"}' \
>    -i input/clinvar_20180429.chr22.pathogenic.vcf.gz \
>    -s ref alt diff \
>    -o /tmp/annotated.vcf
```

I executed it in the root of https://github.com/kipoi/examples where the file `input/...` doesn't exist.

**Comment by krrome** [comment]
I assume this a duplication of / at least related to: https://github.com/kipoi/kipoi/issues/314

**Comment by krrome** [comment]
copy of https://github.com/kipoi/kipoi-veff/issues/18
